### ISSUE TITLE
Review module organisation

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/lsm-tree#106]
Originally discussed in https://github.com/input-output-hk/lsm-tree/pull/98#discussion_r1497261459, I'm recording it in an issue so that we don't forget.

We started with an initial sketch of the module organisation, and we are refining the module organisation as we go. However, we're not doing large-scale reorganisation yet, so we can prevent code churn. When we have a first working version of LSM trees, we can revisit the module org, if necessary.

**Comment by jorisdral** [comment]
We've been doing some module re-organisation with respect to flattening the module structure. Relevant PRs:

[ ] #158
[ ] #159
[ ] #160

**Comment by jorisdral** [comment]
Flattening the module structure + some renaming for consistency
* #164
* #166

**Comment by mheinzel** [comment]
Should I also move `Run.FsPaths` to the top level? The type is already called `RunFsPaths`.

Apart from that, it seems like we changed what we wanted to.

**Comment by jorisdral** [comment]
Feel free to do that and close the issue afterwards!

**Comment by jorisdral** [comment]
I probably missed linking some PRs here, but in any case I'm closing the PR since it seems we've exhausted our module re-org tasks
