### ISSUE TITLE
Missing File Required by Governance

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/lsm-tree#217]
This repo is missing: CODEOWNERS.MD

This document is Required per OSC Governance. https://intersect.gitbook.io/open-source-committee/policies/governance

**Comment by Ranchhand87** [comment]
This issue has been open for 90 days. Please provide an update.

**Comment by mheinzel** [comment]
We have a CODEOWNERS file, it is inside the `.github` directory, one of the possible locations [according to GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location).

https://github.com/IntersectMBO/lsm-tree/blob/main/.github/CODEOWNERS

Is that sufficient?

**Comment by Ranchhand87** [comment]
I realized this does not have the updated verbiage, "If there are CHANGELOG's please create a top level file and link accordingly."
Placing the Changelog or a link thereto, makes it much easier for the community and other developers to quickly find changes and get up to date with Project success.

**Comment by Ranchhand87** [comment]
Apologies, there are many repos that do not show the Changelog on the main page. Please have the CODEOWNERS file moved to the main code.

**Comment by jorisdral** [comment]
We've moved the `CODEOWNERS.md` file to the top-level. @Ranchhand87 let me know if there are other changes we need to make
