### ISSUE TITLE
Assertion failure in `ScheduledMerges` prototype

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/lsm-tree#236]
https://github.com/IntersectMBO/lsm-tree/actions/runs/9351899757/job/25738763256?pr=235

**Comment by mheinzel** [comment]
I found the problem. A last level merge can result in a run of length 0, triggering an underflow issue:

```haskell
tieringRunSizeToLevel r =
    1 + (finiteBitSize s - countLeadingZeros (s-1) - 1) `div` 2
  where
    s = Map.size r
```

I could reproduce the failure using the Quickcheck seed and the error goes away when handling `s == 0` in the calculation above. I will open a PR later.
