### ISSUE TITLE
Test failure in `twiceOpenSession` on Windows

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/lsm-tree#240]
https://github.com/IntersectMBO/lsm-tree/actions/runs/9387087243/job/25849161692#step:15:506

**Comment by jorisdral** [comment]
Another one: https://github.com/IntersectMBO/lsm-tree/actions/runs/9481332529/job/26123889378

**Comment by jorisdral** [comment]
Once again... https://github.com/IntersectMBO/lsm-tree/actions/runs/9758623129/job/26933563088#step:15:809

**Comment by mheinzel** [comment]
Again: https://github.com/IntersectMBO/lsm-tree/actions/runs/10348810698/job/28641858731?pr=333#step:16:674

**Comment by jorisdral** [comment]
Yup, it's been happening intermittently for a while now. Let's see if anything changes after #300
