### ISSUE TITLE
RWVar's bias towards writers cannot possibly behave as intended

### ISSUE THREAD

**Issue by dcoutts** [IntersectMBO/lsm-tree#388]
`unsafeAcquireWriteAccess` involves this snippet of code
```
        | otherwise -> do
            writeTVar var (WaitingToWrite n x)
            retry
```
This doesn't do what it is intended to do. The idea behind this is that if there's several readers already, and a writer comes along, then the writer can "join the queue" and make sure other readers do not "jump the queue" past it. This is to make sure that a writer can eventually do what it needs, without a continuous stream of readers preventing it from making progress.

However the above code does not achieve that aim. It modifies a TVar state and then does `retry`. This discards the state change! It leaves the state variable in the reading state. I think as-is, the state variable cannot ever become `WaitingToWrite` because the only state transition into `WaitingToWrite` is the one where it also does retry to discard the state changes. Which means the behaviour of writers is instead to wait until the state happens to be `Reading 0 x`. So readers can starve out writers.

I think the solution is probably something like this: the writing side needs to do _two_ atomic state changes. First the writer changes it from `Reading n` to `WaitingToWrite n`. And then in a second STM transaction, it waits on the `WaitingToWrite n` n value to reach 0. Of course a second transaction has to consider cases where the state is changed between the transactions too.

**Comment by jorisdral** [comment]
Good catch
