### ISSUE TITLE
New Governance Metric - OSC Governance/Security TWG

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/lsm-tree#391]
Per the Security TWG: Please update/add Security.md

Please refer to: https://github.com/IntersectMBO/Open-Source-Office/blob/main/SECURITY.md

The initial deadline for these changes to be made is 30 September 2024. Thank you.

**Comment by dcoutts** [comment]
@Ranchhand87 can you clarify what you're asking for exactly. I don't know what the TWG is. Do you just mean that we should copy the given `SECURITY.md` into this repository?

**Comment by Ranchhand87** [comment]
@dcoutts Yes please. Copy and update the current Security file to match the new standard for Security.md
